api_platform:

    # enable_swagger_ui: ~
    # enable_re_doc: ~

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
        
    eager_loading:
        enabled: true
    
    collection:
    #     order_parameter_name: '_order'
        pagination:
            # enabled: false
            page_parameter_name: '_page'

            client_enabled: true
            enabled_parameter_name: pagination
            items_per_page: 10 # 30 Default value
            client_items_per_page: true # Disabled by default
            items_per_page_parameter_name: itemsPerPage # Default value
            
            maximum_items_per_page: 10

            # partial: true # Disabled by default
            client_partial: true # Disabled by default
            partial_parameter_name: 'partial' # Default value

    formats:
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        jsonapi:  ['application/vnd.api+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        # yaml:     ['application/x-yaml']
        # csv:      ['text/csv']
        html:     ['text/html']

    exception_to_status:
        App\Exception\EmptyBodyException: 'HTTP_BAD_REQUEST'
        App\Exception\InvalidConfirmationTokenException: 404 

        # Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        # ApiPlatform\Core\Exception\InvalidArgumentException: 'HTTP_BAD_REQUEST' # Or a `Symfony\Component\HttpFoundation\Response`'s constant
        # ApiPlatform\Core\Exception\FilterValidationException: 400
        # Doctrine\ORM\OptimisticLockException: 409
        