vich_uploader:
    db_driver: orm

    mappings:
       images:
           uri_prefix: /images
           upload_destination: '%kernel.project_dir%/public/images'
        #  Decide how to rename uploaded files  
           namer: Vich\UploaderBundle\Naming\UniqidNamer
