PUT http://127.0.0.1:8000/api/blog_posts/12 HTTP/1.1
content-type: application/json 

{
	"title": "From API platform II*wee",
	"content": "API platform test messagexc ",
	"author": "Admin",
	"published": "2018-08-03 16:40:00",
	"slug": "api-test-III"
}